spring.application.name=BookStoreAPI

server.address=0.0.0.0
server.port=5555

spring.datasource.url=jdbc:h2:mem:BookStoreDB
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=britt
spring.datasource.password=2505

spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret = O+ghmLjEJhCduCqD22HE1T2Cgo2hcjET5gz93mi7BLI=
jwt.time = 3600000

